module: CredentialsGitHub
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-CredentialsGitHub/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-CredentialsGitHub.xcodeproj, -target, CredentialsGitHub, -toolchain, org.swift.3020160823a, LIBRARY_SEARCH_PATHS=.build/debug]

